### ISSUE TITLE
Consul cluster support

### ISSUE THREAD

**Issue by moh-abk** [EugenMayer/consul-docker-stability-tests#1]
I've gone through the `bash` scripts in the acls folder and will like to know if this will work in a cluster scenario where you've Consul running on 3 different servers.

I don't have an issue as how the `clients` get the config generated by the server (I can copy that to an S3 bucket etc), not sure how to handle having all 3 servers bootstrap the cluster as each one will generate a different key, certs etc.

**Comment by EugenMayer** [comment]
Well i am not running a cluster setup yet, so i neither have proper experience nor have a reference implementation. So maybe it up to you to PR and add those.

Lets assume, that your are talking about a cluster and not multi-DC, that means we have to care about:

Lets assume, we have 3 `agent servers` ( AS ) now" A, B, C while we plan to make A the first cluster leader. we know need to change our bootstrap to:


 a) only "bootstrap mode" + /ACL/gossip/TLS on A (initial bootstrap)
 b) on every other restart we do no longer want A to start in bootstrap mode i guess ( cleaner way, we can do that )
 
 c) B, C bootstrap as AS, but not in bootstrap mode (never, not even on initial). They need to know where the other cluster members are and will replicate later. They should wait for the `server_agent_acl_token` to exist or for `.bootstrapped` as the `agent clients` do, so they know when the initial leader has been finishing the bootstrap
 d) i think the current "general_acl_token" used as `agent_acl_token` should be enough for B/C to be able to access A for replication. If not, we have to generate a new ACL for the cluster server members for the server2server comms and replication (needs testing). If we create a new agent_acl_token we should name it `server_agent_acl_token` and create an ACL, store it in the config directory and let B/C load it

- For c) / d) we need a new bootstrap flag or detection, when to boot in "non bootstrap mode". I opt in for an ENV flag since AFAIU, we need to select the initial "leader" ourselfs, that cannot be an automation, means we start 1 with bootstrap flag and 2 without ( manual ENV config )

Network:
i assume you have a not "spanned" network across the different nodes ( hosts ) so that is something we need to care about - we need to expose the ports we need ( which ones ) on the host in docker-compose.yml (all 3 cluster AS need that) and then we need to implement a ENV var which will set the advertised address so A/B/C know how to reach eachother using the external network.

-------

Be sure, that was a theoretical go at this, not tried yet but i am eager to follow you on that and also enrich the bootstrap to support that
